update and handle all the exit code

diff --git a/.github/workflows/security-pipeline.yml b/.github/workflows/security-pipeline.yml
--- a/.github/workflows/security-pipeline.yml
+++ b/.github/workflows/security-pipeline.yml
@@ -265,8 +265,21 @@ jobs:
 
       - name: Evaluate root pod scenario
         run: |
+          set +e
+
           kyverno apply k8s/kyverno-policies.yaml \
             --resource k8s/evals/root-pod.yaml
+
+          EXIT_CODE=$?
+
+          if [ "$EXIT_CODE" -eq 0 ]; then
+            echo "::error::Security test failed - root pod was allowed."
+            exit 1
+          fi
+
+          echo "Expected security violation detected."
+          echo "Root pod was correctly blocked by Kyverno."
+          exit 0
 
       - name: Evaluate missing resource limits scenario
         run: |
@@ -288,8 +301,18 @@ jobs:
 
       - name: Evaluate unauthorized network scenario
         run: |
-          kubectl apply \
-            --dry-run=client \
-            -f k8s/evals/unauthorized-network-access.yaml
-          
-    
+          set +e
+
+          kyverno apply k8s/kyverno-policies.yaml \
+            --resource k8s/evals/unauthorized-network-access.yaml
+
+          EXIT_CODE=$?
+
+          if [ "$EXIT_CODE" -eq 0 ]; then
+            echo "::error::Security test failed - unauthorized network configuration was allowed."
+            exit 1
+          fi
+
+          echo "Expected security violation detected."
+          echo "Unauthorized network configuration was correctly blocked by Kyverno."
+          exit 0
